require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'

Style:
  Enabled: false

Bundler/GemFilename:
  EnforcedStyle: gems.rb

Metrics/AbcSize:
  Max: 25

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9

