require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - 'vendor/**/*'

Style:
  Enabled: false

Bundler/GemFilename:
  EnforcedStyle: Gemfile

Metrics/AbcSize:
  Max: 25

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/MethodLength:
  Max: 12

Metrics/ParameterLists:
  Max: 8

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/PerceivedComplexity:
  Max: 9
