version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0 

jobs:
  build:
    docker:
      - image: cimg/ruby:2.5.9
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/install-deps
      - ruby/rubocop-check
      - ruby/rspec-test

