version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0 

jobs:
  min-rspec:
    docker:
      - image: cimg/ruby:2.5
    environment:
      GEM_VERSIONS: min
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle install
      - ruby/rubocop-check
      - ruby/rspec-test
  max-rspec:
    docker:
      - image: cimg/ruby:3.2
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle install
      - ruby/rubocop-check
      - ruby/rspec-test

workflows:
  build:
    jobs:
      - min-rspec
      - max-rspec