version: 2.1
orbs:
  ruby: circleci/ruby@0.2.2 

jobs:
  build:
    docker:
      - image: cimg/ruby:2.5.9
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          command: bin/rubocop
      - run:
          command: bin/rspec
