version: 2.1

commands:
  run-rspec:
    steps:
      - run: bundle install
      - run: bin/rspec

jobs:
  min-rspec:
    docker:
      - image: cimg/ruby:2.5
    environment:
      GEM_VERSIONS: min
    steps:
      - checkout
      - run-rspec
  max-rspec:
    docker:
      - image: cimg/ruby:3.2
    steps:
      - checkout
      - run-rspec
      - run: bin/rubocop

workflows:
  build:
    jobs:
      - min-rspec
      - max-rspec